// GENERATED by firmware/bio_node/filter_design.py - do not edit by hand.
// Sections are {b0, b1, b2, a1, a2} (a0 = 1), direct form II transposed, fs = 1000 Hz.
#pragma once
#define BIO_FS_HZ 1000
#define BIO_BP_SECTIONS 2
#define BIO_LP_SECTIONS 1
#define BIO_DC_ALPHA 0.001f
// Band-pass 74.5-149.5 Hz, Butterworth, 4th order (2 biquads)
static const float BIO_BP_SOS[BIO_BP_SECTIONS][5] = {
  {4.1253537242e-02f, 8.2507074483e-02f, 4.1253537242e-02f, -1.0841989560e+00f, 6.6683102898e-01f},
  {1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f, -1.5417516451e+00f, 7.7078280987e-01f}
};
// Envelope low-pass 20.0 Hz, Butterworth, 2nd order (1 biquad)
static const float BIO_LP_SOS[BIO_LP_SECTIONS][5] = {
  {3.6216815149e-03f, 7.2433630299e-03f, 3.6216815149e-03f, -1.8226949252e+00f, 8.3718165126e-01f}
};
