#!/usr/bin/env python3
"""Design the Node B (bio_node) filters and write filter_coeffs.h.

Run:  python firmware/bio_node/filter_design.py          (rewrites filter_coeffs.h)
      python firmware/bio_node/filter_design.py --check  (exit 1 if the header is stale)

Own design (no third-party code, so no licence question): same band as the Upside Down Labs EMG filter
(74.5-149.5 Hz at 1 kHz sampling), built as a 4th-order Butterworth band-pass (two biquad sections,
scipy butter(N=2, 'bandpass') gives 2*N = 4 poles -> 4th order), then a 2nd-order Butterworth
20 Hz low-pass for the envelope (10 Hz, as in the PRD, measures 50 ms to 90 % on the host test; the
acceptance bar is < 40 ms, so the corner is 20 Hz - recorded as a SPEC request). Both are applied as cascaded direct-form-II-transposed biquads in float.

Chain in firmware (1 kHz):  adc -> DC removal -> band-pass -> |x| -> envelope LPF -> every 10th sample (100 Hz)
"""
import sys
from pathlib import Path

import numpy as np
from scipy.signal import butter

FS = 1000.0
BP_LO, BP_HI = 74.5, 149.5
BP_ORDER = 2          # scipy: order per band edge; the band-pass is 2*BP_ORDER = 4th order
ENV_FC = 20.0         # PRD says 10 Hz; a 2nd-order 10 Hz LPF needs ~50 ms to reach 90 % (acceptance: < 40 ms). See log.
ENV_ORDER = 2
DC_ALPHA = 0.001      # DC tracker: dc += alpha*(x-dc); corner ~0.16 Hz at 1 kHz

HEADER = Path(__file__).with_name("filter_coeffs.h")


def design():
    bp = butter(BP_ORDER, [BP_LO, BP_HI], btype="bandpass", fs=FS, output="sos")
    lp = butter(ENV_ORDER, ENV_FC, btype="lowpass", fs=FS, output="sos")
    return bp, lp


def _fmt(sos):
    rows = []
    for s in sos:
        b0, b1, b2, a0, a1, a2 = s
        assert abs(a0 - 1.0) < 1e-12
        rows.append("  {%.10ef, %.10ef, %.10ef, %.10ef, %.10ef}" % (b0, b1, b2, a1, a2))
    return ",\n".join(rows)


def render():
    bp, lp = design()
    return f"""// GENERATED by firmware/bio_node/filter_design.py - do not edit by hand.
// Sections are {{b0, b1, b2, a1, a2}} (a0 = 1), direct form II transposed, fs = {FS:.0f} Hz.
#pragma once
#define BIO_FS_HZ {FS:.0f}
#define BIO_BP_SECTIONS {len(bp)}
#define BIO_LP_SECTIONS {len(lp)}
#define BIO_DC_ALPHA {DC_ALPHA}f
// Band-pass {BP_LO}-{BP_HI} Hz, Butterworth, 4th order ({len(bp)} biquads)
static const float BIO_BP_SOS[BIO_BP_SECTIONS][5] = {{
{_fmt(bp)}
}};
// Envelope low-pass {ENV_FC} Hz, Butterworth, 2nd order ({len(lp)} biquad)
static const float BIO_LP_SOS[BIO_LP_SECTIONS][5] = {{
{_fmt(lp)}
}};
"""


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        sys.exit(0 if cur == text else 1)
    HEADER.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {HEADER}")
    bp, lp = design()
    print("BP sos:\n", bp, "\nLP sos:\n", lp)
